// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Address is a postal address of an identity or a card.
 */
export interface Address {
    /**
     * ID is an identity address's stable hex id, empty for a new one and for a card's address.
     */
    "id": string;
    "label": string;
    "street": string;
    "city": string;
    "region": string;
    "postalCode": string;
    "country": string;
}

/**
 * AddressLink names one address of one identity by their hex ids.
 */
export interface AddressLink {
    "identityId": string;
    "addressId": string;
}

/**
 * Appearance reports whether the interface is light, dark or follows the system, and the appearances offered.
 */
export interface Appearance {
    "appearance": string;
    "offered": string[] | null;
}

/**
 * AutoBackup is the automatic backup setting of the open vault and the choices offered.
 */
export interface AutoBackup {
    "enabled": boolean;
    "interval": string;
    "intervals": string[] | null;
    "keep": number;
    "keeps": number[] | null;
    "folder": BackupFolder | null;

    /**
     * LastBackupAt is in Unix milliseconds, zero for never.
     */
    "lastBackupAt": number;

    /**
     * Failed reports that the last attempt for the open vault failed.
     */
    "failed": boolean;
}

/**
 * AutoLock is the automatic lock setting and the delays offered.
 */
export interface AutoLock {
    "enabled": boolean;

    /**
     * Seconds counts from the last input, or from hiding the app under LockWhenHidden, where zero locks at once.
     */
    "seconds": number;
    "offered": number[] | null;
}

/**
 * BackupCode is one backup code and whether it was used.
 */
export interface BackupCode {
    "value": string;
    "used": boolean;
}

/**
 * BackupFolder is how the interface shows the folder backups go to.
 */
export interface BackupFolder {
    "name": string;
    "place": string;
}

/**
 * BankDetails reports whether a card's bank name and colour are looked up on the bank's site.
 */
export interface BankDetails {
    "enabled": boolean;
}

/**
 * BankLookup is what a bank's site declares; either field is empty when unusable.
 */
export interface BankLookup {
    "name": string;

    /**
     * Color is "#rrggbb".
     */
    "color": string;
}

/**
 * Capabilities are the features this host offers beyond the vault.
 */
export interface Capabilities {
    /**
     * Extensions reports that browser extensions can link to this host.
     */
    "extensions": boolean;

    /**
     * Shortcuts reports that the interface takes keyboard shortcuts.
     */
    "shortcuts": boolean;

    /**
     * DockIcon reports that the host has a Dock icon it can hide with its window.
     */
    "dockIcon": boolean;

    /**
     * StorageLocations reports that the owner can open a vault file and choose where a new one lives.
     */
    "storageLocations": boolean;

    /**
     * SaveFiles reports that the host saves files where the owner chooses; Host.Saver sets it.
     */
    "saveFiles": boolean;

    /**
     * UnlockOnShow reports that the locked screen asks for device unlock as the app comes into view.
     */
    "unlockOnShow": boolean;

    /**
     * InterfaceSize reports that the owner sets the interface size in settings.
     */
    "interfaceSize": boolean;

    /**
     * Appearance reports that the host's windows follow the light, dark or system appearance chosen in settings.
     */
    "appearance": boolean;

    /**
     * PhotoPicker reports a photo picker apart from the file picker PDF scans still come from.
     */
    "photoPicker": boolean;

    /**
     * IdentityList reports that the system can keep the vault's accounts to suggest in its own autofill.
     */
    "identityList": boolean;

    /**
     * CopyScans reports that the host puts a scan on the clipboard.
     */
    "copyScans": boolean;

    /**
     * LockWhenHidden reports that the automatic lock counts from hiding the app and can lock at once.
     */
    "lockWhenHidden": boolean;

    /**
     * Screenshots reports that windows stay out of screenshots unless the owner allows them.
     */
    "screenshots": boolean;

    /**
     * SystemAutofill reports that the owner picks the autofill service and passkey provider on a system screen.
     */
    "systemAutofill": boolean;

    /**
     * AutoBackups reports that the host backs up the open vault into a folder the owner chooses.
     */
    "autoBackups": boolean;

    /**
     * Print reports that the host prints through the system print dialog; Host.Printer sets it.
     */
    "print": boolean;

    /**
     * QRCodes reports that the editor reads a one-time code setup from a QR code picture; Host.QRCodes sets it.
     */
    "qrCodes": boolean;
}

/**
 * Card is a card as read.
 */
export interface Card {
    "id": string;
    "groups": string[] | null;
    "site": string;

    /**
     * Linked is the address the billing link names, null without a link or once that address is gone.
     */
    "linked": LinkedAddress | null;
    "label": string;
    "holder": string;
    "number": string;
    "expiry": string;
    "securityCode": string;
    "pin": string;

    /**
     * Network is a credit-card-type name such as "visa" or "american-express", empty for none.
     */
    "network": string;
    "bankName": string;
    "bankSite": string;
    "color": string;

    /**
     * Billing is the card's own address.
     */
    "billing": Address | null;

    /**
     * BillingLink names an identity's address.
     */
    "billingLink": AddressLink | null;
    "notes": string;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * CardInput is the editable content of a card; at most one of Billing and BillingLink is set.
 */
export interface CardInput {
    "label": string;
    "holder": string;
    "number": string;
    "expiry": string;
    "securityCode": string;
    "pin": string;

    /**
     * Network is a credit-card-type name such as "visa" or "american-express", empty for none.
     */
    "network": string;
    "bankName": string;
    "bankSite": string;
    "color": string;

    /**
     * Billing is the card's own address.
     */
    "billing": Address | null;

    /**
     * BillingLink names an identity's address.
     */
    "billingLink": AddressLink | null;
    "notes": string;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * CardLimits are the vault core's card text lengths in characters and digit counts for number, code and PIN.
 */
export interface CardLimits {
    "label": number;
    "holder": number;
    "numberMin": number;
    "numberMax": number;
    "securityCodeMin": number;
    "securityCodeMax": number;
    "pinMin": number;
    "pinMax": number;
    "bankName": number;
    "bankSite": number;
    "street": number;
    "city": number;
    "region": number;
    "postalCode": number;
    "country": number;
    "notes": number;
}

/**
 * CardSummary is a card as the list shows it; empty strings mean none.
 */
export interface CardSummary {
    "id": string;
    "label": string;
    "bankName": string;
    "lastFour": string;
    "network": string;
    "color": string;

    /**
     * Site is the host of the bank's site.
     */
    "site": string;
    "pinned": boolean;
    "lastUsedAt": number;
    "groups": string[] | null;
    "tags": string[] | null;

    /**
     * ExpiresOn is the last day of the expiry month as YYYY-MM-DD.
     */
    "expiresOn": string;
}

/**
 * ClipboardClearing is the clipboard clearing setting and the delays offered.
 */
export interface ClipboardClearing {
    "enabled": boolean;
    "seconds": number;
    "offered": number[] | null;
}

/**
 * CodeSetup is the one-time code setup waiting for the owner, without its secret.
 */
export interface CodeSetup {
    "pending": boolean;

    /**
     * Token names the setup to the calls acting on it.
     */
    "token": string;
    "issuer": string;
    "account": string;
}

/**
 * Confirmation is a request waiting in the confirmation panel; fields a request does not name are empty.
 */
export interface Confirmation {
    "id": string;

    /**
     * Kind is "verify" or "unlock".
     */
    "kind": string;

    /**
     * Reason is "share", "save-passkey", "sign-in", "fill" or "change-unlock" for a verify request.
     */
    "reason": string;
    "file": string;
    "identity": string;
    "site": string;
    "account": string;

    /**
     * Requester is "extension" or "autofill" for an unlock request.
     */
    "requester": string;
}

/**
 * Credential is an opened credential with its groups and passkeys.
 */
export interface Credential {
    "id": string;
    "groups": string[] | null;
    "site": string;
    "passkeys": PasskeyView[] | null;
    "label": string;
    "websites": string[] | null;
    "login": string;
    "email": string;
    "password": string;
    "notes": string;
    "totp": string;

    /**
     * Apps are the apps the credential signs in to. A new credential has none.
     */
    "apps": LinkedApp[] | null;

    /**
     * Tags tell the item apart from others like it, such as two accounts on one site.
     */
    "tags": string[] | null;
}

/**
 * CredentialInput is the editable content of a credential.
 */
export interface CredentialInput {
    "label": string;
    "websites": string[] | null;
    "login": string;
    "email": string;
    "password": string;
    "notes": string;
    "totp": string;

    /**
     * Apps are the apps the credential signs in to. A new credential has none.
     */
    "apps": LinkedApp[] | null;

    /**
     * Tags tell the item apart from others like it, such as two accounts on one site.
     */
    "tags": string[] | null;
}

/**
 * CredentialLimits are the vault core's credential field lengths in characters and the most websites.
 */
export interface CredentialLimits {
    "label": number;
    "website": number;
    "websites": number;
    "login": number;
    "email": number;
    "password": number;
    "notes": number;
    "totp": number;
}

/**
 * CredentialSummary is a credential as the list shows it.
 */
export interface CredentialSummary {
    "id": string;
    "label": string;
    "login": string;

    /**
     * Site is the host the website icon is keyed by, empty when no website names a site.
     */
    "site": string;

    /**
     * Sites are the distinct hosts of the credential's websites in order, Site first.
     */
    "sites": string[] | null;
    "email": string;
    "pinned": boolean;
    "lastUsedAt": number;
    "groups": string[] | null;
    "tags": string[] | null;

    /**
     * Sites, OneTimeCode and Passkeys come from the index, without decrypting the record.
     */
    "oneTimeCode": boolean;
    "passkeys": number;
}

/**
 * DockIcon reports whether Ravenpass leaves the Dock while its window is closed.
 */
export interface DockIcon {
    "hideWithWindow": boolean;
}

/**
 * ExportStatus reports whether the last encrypted copy matches the vault.
 */
export interface ExportStatus {
    "state": string;
}

/**
 * ExtensionLinkOffer is a one-time connection key waiting for an extension.
 */
export interface ExtensionLinkOffer {
    "key": string;

    /**
     * ExpiresAt is in Unix milliseconds.
     */
    "expiresAt": number;
}

/**
 * ExtensionLinks lists the linked extensions, and whether they can reach this app.
 */
export interface ExtensionLinks {
    "extensions": LinkedExtension[] | null;
    "reachable": boolean;
}

/**
 * Group is a name the person gave a set of credentials. It carries no credential data.
 */
export interface Group {
    "id": string;
    "name": string;
}

/**
 * Identity is an identity as read.
 */
export interface Identity {
    "id": string;
    "groups": string[] | null;

    /**
     * Attachments describes every scan its documents name.
     */
    "attachments": ScanSummary[] | null;
    "label": string;
    "fullName": string;
    "birthday": string;
    "emails": string[] | null;
    "phones": string[] | null;
    "addresses": Address[] | null;
    "documents": IdentityDocument[] | null;
    "notes": string;

    /**
     * Photo is base64, empty for none: the stored photo as read or the PNG CropIdentityPhoto returned.
     */
    "photo": string;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * IdentityAddresses is what a card's billing address can link to in one identity.
 */
export interface IdentityAddresses {
    "identityId": string;
    "label": string;
    "addresses": Address[] | null;
}

/**
 * IdentityDocument is one document of an identity.
 */
export interface IdentityDocument {
    /**
     * Type is "passport", "drivers-license", "id-card", "tax-number" or "other".
     */
    "type": string;
    "label": string;
    "number": string;
    "issuer": string;
    "issuedOn": string;
    "expiresOn": string;

    /**
     * Scans are attachment ids, passed back as read on edit, or "new:" tokens of staged scans.
     */
    "scans": string[] | null;
}

/**
 * IdentityField names one copyable identity value.
 */
export interface IdentityField {
    /**
     * Kind is "fullName", "birthday", "notes", "email", "phone", "address" or "document".
     */
    "kind": string;

    /**
     * Index is the zero-based position in the Kind's list.
     */
    "index"?: number;

    /**
     * Part names one part of an address alone.
     */
    "part"?: string;
}

/**
 * IdentityInput is the editable content of an identity.
 */
export interface IdentityInput {
    "label": string;
    "fullName": string;
    "birthday": string;
    "emails": string[] | null;
    "phones": string[] | null;
    "addresses": Address[] | null;
    "documents": IdentityDocument[] | null;
    "notes": string;

    /**
     * Photo is base64, empty for none: the stored photo as read or the PNG CropIdentityPhoto returned.
     */
    "photo": string;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * IdentityLimits are the vault core's identity text lengths in characters and list sizes.
 */
export interface IdentityLimits {
    "label": number;
    "fullName": number;
    "email": number;
    "phone": number;
    "addressLabel": number;
    "street": number;
    "city": number;
    "region": number;
    "postalCode": number;
    "country": number;
    "documentLabel": number;
    "documentNumber": number;
    "issuer": number;
    "notes": number;
    "emails": number;
    "phones": number;
    "addresses": number;
    "documents": number;
}

/**
 * IdentityListSetting reports whether the system keeps the vault's websites and user names for its autofill.
 */
export interface IdentityListSetting {
    "enabled": boolean;
}

/**
 * IdentitySummary is an identity as the list shows it; empty strings mean none.
 */
export interface IdentitySummary {
    "id": string;
    "label": string;

    /**
     * Email is the first email.
     */
    "email": string;
    "pinned": boolean;
    "lastUsedAt": number;
    "groups": string[] | null;
    "tags": string[] | null;

    /**
     * ExpiresOn is the earliest document expiry as YYYY-MM-DD.
     */
    "expiresOn": string;

    /**
     * Thumbnail is the photo as a base64 JPEG.
     */
    "thumbnail": string;
}

/**
 * ImportChoice is the export the person chose; Chosen is false for a canceled picker.
 */
export interface ImportChoice {
    "chosen": boolean;
    "name": string;

    /**
     * Locked is true for a file that needs its password before it has a preview.
     */
    "locked": boolean;
    "preview": ImportPreview;
}

/**
 * ImportConversion counts items of source kind From that become another kind.
 */
export interface ImportConversion {
    "from": string;
    "count": number;
}

/**
 * ImportGroups is what the folders of the imported items come to.
 */
export interface ImportGroups {
    "new": number;
    "existing": number;

    /**
     * Dropped counts folders that cannot become groups.
     */
    "dropped": number;
}

/**
 * ImportKind is what an import adds of one kind, with duplicates kept.
 */
export interface ImportKind {
    "kind": string;
    "count": number;

    /**
     * Duplicates counts items the vault already holds.
     */
    "duplicates": number;
    "oneTimeCodes": number;

    /**
     * Converted counts items arriving from another kind of the source.
     */
    "converted": ImportConversion[] | null;
}

/**
 * ImportKindTotal counts the items an import added of one kind.
 */
export interface ImportKindTotal {
    "kind": string;
    "count": number;
}

/**
 * ImportOptions are the person's import choices.
 */
export interface ImportOptions {
    "groups": boolean;
    "skipDuplicates": boolean;

    /**
     * CardNetworks maps each previewed card issuer to a network name cards use.
     */
    "cardNetworks": { [_ in string]?: string } | null;
}

/**
 * ImportPreview is what an import adds and leaves behind, known before anything is written.
 */
export interface ImportPreview {
    "format": string;
    "items": number;
    "kinds": ImportKind[] | null;

    /**
     * Groups counts folders with duplicates kept, GroupsWithoutDuplicates with them skipped.
     */
    "groups": ImportGroups;
    "groupsWithoutDuplicates": ImportGroups;

    /**
     * CardIssuers are the issuer identification numbers of cards that name no network.
     */
    "cardIssuers": string[] | null;
    "skipped": ImportSkip[] | null;
    "attachments": number;

    /**
     * Passkeys counts passkeys left behind.
     */
    "passkeys": number;

    /**
     * ImportedPasskeys counts passkeys brought over with duplicates kept.
     */
    "importedPasskeys": number;
}

/**
 * ImportResult is what an import added.
 */
export interface ImportResult {
    "added": number;
    "kinds": ImportKindTotal[] | null;
    "groups": number;

    /**
     * Format tells whether the source file still holds the passwords unencrypted.
     */
    "format": string;

    /**
     * Located is false for a file picked as a temporary copy, which Ravenpass cannot trash or reveal.
     */
    "located": boolean;
}

/**
 * ImportSkip is an item the import cannot add.
 */
export interface ImportSkip {
    "label": string;

    /**
     * Origin is empty for a type the source reader does not know.
     */
    "origin": string;
    "reason": string;
}

/**
 * InterfaceSize is the chosen interface size and the sizes offered, in percent.
 */
export interface InterfaceSize {
    "percent": number;
    "offered": number[] | null;
}

/**
 * LanguageSettings reports the languages Ravenpass offers and the one in use.
 */
export interface LanguageSettings {
    "languages": string[] | null;

    /**
     * Language is, until one is chosen, the device's language when offered, else English.
     */
    "language": string;
    "chosen": boolean;
}

/**
 * LinkedAddress is the identity address a card's billing link names.
 */
export interface LinkedAddress {
    "identityLabel": string;
    "address": Address;
}

/**
 * LinkedApp is an Android app a credential signs in to; only autofill links one.
 */
export interface LinkedApp {
    "package": string;

    /**
     * Signer is the lower-case hex SHA-256 digest of one signing certificate.
     */
    "signer": string;

    /**
     * Name is what the app installed on this device shows as its name; empty where the device has no such app.
     */
    "name": string;
}

/**
 * LinkedExtension is a browser extension linked to this app.
 */
export interface LinkedExtension {
    "id": string;
    "name": string;

    /**
     * LinkedAt is in Unix milliseconds.
     */
    "linkedAt": number;
}

/**
 * Note is an opened note with its groups.
 */
export interface Note {
    "id": string;
    "groups": string[] | null;
    "label": string;
    "body": string;
    "hidden": boolean;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * NoteInput is one note. A hidden note shows no preview in the list.
 */
export interface NoteInput {
    "label": string;
    "body": string;
    "hidden": boolean;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * NoteLimits are the vault core's note bounds, counted in characters.
 */
export interface NoteLimits {
    "label": number;
    "body": number;
}

/**
 * NoteSummary is a note as the list shows it.
 */
export interface NoteSummary {
    "id": string;
    "label": string;

    /**
     * Preview is the first line of the body holding text, empty for a hidden note.
     */
    "preview": string;
    "hidden": boolean;
    "pinned": boolean;
    "lastUsedAt": number;
    "groups": string[] | null;
    "tags": string[] | null;
}

/**
 * OneTimeCode is the code a credential's setup produces now.
 */
export interface OneTimeCode {
    "code": string;
    "digits": number;
    "period": number;

    /**
     * ExpiresAt is in Unix milliseconds.
     */
    "expiresAt": number;
}

/**
 * PasskeyView is a credential's passkey as the workspace shows it, without its key.
 */
export interface PasskeyView {
    /**
     * ID is the credential ID in unpadded base64url.
     */
    "id": string;

    /**
     * Site is the relying party ID.
     */
    "site": string;
    "account": string;
    "displayName": string;

    /**
     * CreatedAt is in Unix milliseconds.
     */
    "createdAt": number;
}

/**
 * PhotoDraft is the chosen picture's preview; Chosen is false for a canceled dialog.
 */
export interface PhotoDraft {
    "chosen": boolean;

    /**
     * Preview is a base64 JPEG of Width by Height pixels.
     */
    "preview": string;
    "width": number;
    "height": number;
}

/**
 * PhraseCheck is the BIP-39 check of a typed phrase.
 */
export interface PhraseCheck {
    "checksum": string;

    /**
     * UnknownWords are the zero-based positions of words outside the BIP-39 list.
     */
    "unknownWords": number[] | null;
}

/**
 * RecoveryPreview is what confirming a staged recovery would do.
 */
export interface RecoveryPreview {
    "mayLoseNewerCredentials": boolean;

    /**
     * KeyReplaced is true when the file is sealed under a recovery key this device saw replaced.
     */
    "keyReplaced": boolean;

    /**
     * NeedsWayIn is true when this device holds no way in that still opens the vault.
     */
    "needsWayIn": boolean;
}

/**
 * ScanDraft is a chosen scan staged for the editor's save; Chosen is false for a canceled dialog.
 */
export interface ScanDraft {
    "chosen": boolean;

    /**
     * Token names the draft in a document's scans as "new:" followed by Token.
     */
    "token": string;
    "name": string;
    "mediaType": string;
    "thumbnail": string;
}

/**
 * ScanSaved reports whether a copy was written.
 */
export interface ScanSaved {
    "saved": boolean;
}

/**
 * ScanSummary describes one scan without its content.
 */
export interface ScanSummary {
    "id": string;
    "name": string;

    /**
     * MediaType is image/jpeg or application/pdf.
     */
    "mediaType": string;

    /**
     * Thumbnail is a base64 JPEG for a picture and empty for a PDF.
     */
    "thumbnail": string;
}

/**
 * Seed is a seed as read.
 */
export interface Seed {
    "id": string;
    "groups": string[] | null;

    /**
     * CheckedOn is empty or the YYYY-MM-DD day its copy was last confirmed.
     */
    "checkedOn": string;

    /**
     * Checksum is "valid", "invalid" or "unknown" for a phrase, and empty for another format.
     */
    "checksum": string;
    "label": string;

    /**
     * Format is "phrase" (Words, Passphrase, Path), "key" (Key) or "codes" (Codes).
     */
    "format": string;
    "words": string[] | null;
    "passphrase": string;
    "path": string;
    "key": string;
    "codes": BackupCode[] | null;
    "wallet": string;
    "addresses": SeedAddress[] | null;
    "notes": string;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * SeedAddress is one labelled address a seed's wallet receives at.
 */
export interface SeedAddress {
    "label": string;
    "value": string;
}

/**
 * SeedField names one copyable seed value.
 */
export interface SeedField {
    /**
     * Kind is "phrase", "passphrase", "path", "key", "notes" or "address".
     */
    "kind": string;

    /**
     * Index is the zero-based position of an address.
     */
    "index"?: number;
}

/**
 * SeedInput is one seed; fields of a format other than Format are empty.
 */
export interface SeedInput {
    "label": string;

    /**
     * Format is "phrase" (Words, Passphrase, Path), "key" (Key) or "codes" (Codes).
     */
    "format": string;
    "words": string[] | null;
    "passphrase": string;
    "path": string;
    "key": string;
    "codes": BackupCode[] | null;
    "wallet": string;
    "addresses": SeedAddress[] | null;
    "notes": string;

    /**
     * Tags tell the item apart from others like it.
     */
    "tags": string[] | null;
}

/**
 * SeedLimits are the vault core's seed text lengths in characters and list sizes.
 */
export interface SeedLimits {
    "label": number;
    "words": number;
    "word": number;
    "passphrase": number;
    "path": number;
    "key": number;
    "codes": number;
    "code": number;
    "wallet": number;
    "addresses": number;
    "addressLabel": number;
    "address": number;
    "notes": number;
}

/**
 * SeedSummary is a seed as the list shows it.
 */
export interface SeedSummary {
    "id": string;
    "label": string;
    "format": string;
    "wallet": string;

    /**
     * Total is the word count of a phrase, 0 for a private key and the code count of backup codes.
     */
    "total": number;

    /**
     * Used is the used backup code count, 0 for other formats.
     */
    "used": number;
    "pinned": boolean;
    "lastUsedAt": number;
    "groups": string[] | null;
    "tags": string[] | null;
}

/**
 * SignInStyle reports how a linked extension offers sign-in on websites and the styles offered.
 */
export interface SignInStyle {
    "style": string;
    "offered": string[] | null;
}

/**
 * SiteIcon is a site's icon.
 */
export interface SiteIcon {
    /**
     * Image is a base64 PNG, empty for none.
     */
    "image": string;

    /**
     * Tint is the main colour as "#rrggbb", empty for a grey icon or none.
     */
    "tint": string;
}

/**
 * SiteIcons reports whether website icons load.
 */
export interface SiteIcons {
    "enabled": boolean;
}

/**
 * SiteLookup is what a credential's typed or pasted website suggests.
 */
export interface SiteLookup {
    /**
     * Name is the site's declared name or its readable domain.
     */
    "name": string;

    /**
     * Website is the address cut to what the vault matches it by, as imports keep it.
     */
    "website": string;
}

/**
 * State is the phase of the vault the interface shows.
 */
export interface State {
    "phase": string;
}

/**
 * StorageChange reports what a location action did; Changed is false after a cancel or declined authentication.
 */
export interface StorageChange {
    "changed": boolean;
    "path": string;
    "previous": Vault;
    "previousRemoved": boolean;
}

/**
 * StorageStatus describes where the current vault is kept and which storage kinds are offered.
 */
export interface StorageStatus {
    "kinds": string[] | null;

    /**
     * Chosen lists the kinds whose file the owner picks; the others live where the host keeps them.
     */
    "chosen": string[] | null;
    "kind": string;
    "path": string;
    "name": string;
    "place": string;
    "vaults": Vault[] | null;
    "available": boolean;
    "restricted": boolean;
    "reason": string;

    /**
     * Shared reports a file other devices may open: anywhere but the folder the host keeps its own vaults in.
     */
    "shared": boolean;

    /**
     * Missing reports that the file this device opened the vault from is gone from the current location.
     */
    "missing": boolean;
}

/**
 * SupportDetails are the technical facts a problem report carries; none names the device, its owner or a vault.
 */
export interface SupportDetails {
    "platform": string;
    "osVersion": string;
}

/**
 * SystemAutofillStatus is what the device has chosen Ravenpass for.
 */
export interface SystemAutofillStatus {
    /**
     * Autofill reports that Ravenpass is the device's autofill service.
     */
    "autofill": boolean;

    /**
     * Passkeys reports that Ravenpass is one of the device's passkey providers.
     */
    "passkeys": boolean;

    /**
     * PasskeyProviders reports that the device takes passkey providers; when false, Passkeys is false too.
     */
    "passkeyProviders": boolean;
}

/**
 * TagLimits bound the tags of one item: each tag's length in characters and their count.
 */
export interface TagLimits {
    "tag": number;
    "tags": number;
}

/**
 * UnlockChoice is how a vault being created or recovered will open on this device.
 */
export interface UnlockChoice {
    "biometry": boolean;

    /**
     * PIN is empty when no PIN is chosen.
     */
    "pin": string;
}

/**
 * UnlockMethods reports the ways into the bound vault this device has and the PIN length bounds.
 */
export interface UnlockMethods {
    "biometryAvailable": boolean;
    "biometryEnabled": boolean;
    "pinSet": boolean;
    "pinAttemptsLeft": number;
    "pinMinLength": number;
    "pinMaxLength": number;
}

/**
 * Vault is one of the vaults this device knows.
 */
export interface Vault {
    "kind": string;

    /**
     * Path identifies the vault.
     */
    "path": string;

    /**
     * Name is the file's name.
     */
    "name": string;

    /**
     * Place is where the file is kept, in words.
     */
    "place": string;
    "current": boolean;
}

/**
 * VaultDeletion reports what a permanent deletion left on this device.
 */
export interface VaultDeletion {
    /**
     * Deleted is false when the owner declined device authentication, which changes nothing.
     */
    "deleted": boolean;
    "path": string;
    "deviceRecordsRemoved": boolean;
    "sharedIdentity": boolean;
}
