// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the vault application service bound to the interface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCodeSetup makes the waiting setup token names the one-time code of credential credentialID.
 */
export function AddCodeSetup(token: string, credentialID: string): $CancellablePromise<void> {
    return $Call.ByID(2990560693, token, credentialID);
}

/**
 * AdoptChangedVault opens a vault whose unlock failed as diverged, discarding this device's latest changes.
 */
export function AdoptChangedVault(): $CancellablePromise<void> {
    return $Call.ByID(2634264444);
}

/**
 * AllowScreenshots records and applies whether the main window may be captured; other windows never may.
 */
export function AllowScreenshots(allowed: boolean): $CancellablePromise<void> {
    return $Call.ByID(1274947336, allowed);
}

/**
 * AwaitConfirmation returns the oldest waiting request other than shown, or empty once none waits unless shown is empty.
 */
export function AwaitConfirmation(shown: string): $CancellablePromise<$models.Confirmation> {
    return $Call.ByID(532798529, shown);
}

/**
 * AwaitExtensionLink returns the extension that links with the waiting key; canceling the call cancels the key.
 */
export function AwaitExtensionLink(): $CancellablePromise<$models.LinkedExtension> {
    return $Call.ByID(1098202149);
}

/**
 * AwaitLanguageChange returns the count of language choices since start once it passes seen.
 */
export function AwaitLanguageChange(seen: number): $CancellablePromise<number> {
    return $Call.ByID(4124714594, seen);
}

/**
 * AwaitVaultChange returns the count of changes made outside the interface once it passes seen.
 */
export function AwaitVaultChange(seen: number): $CancellablePromise<number> {
    return $Call.ByID(161382512, seen);
}

/**
 * BeginCreation stages a new vault and returns its recovery phrase.
 */
export function BeginCreation(): $CancellablePromise<string> {
    return $Call.ByID(2620458318);
}

/**
 * BeginExtensionLink creates a one-time connection key, replacing the one waiting.
 */
export function BeginExtensionLink(): $CancellablePromise<$models.ExtensionLinkOffer> {
    return $Call.ByID(2424646952);
}

/**
 * BeginRecovery stages recovery of the vault with phrase and previews its effect.
 */
export function BeginRecovery(phrase: string): $CancellablePromise<$models.RecoveryPreview> {
    return $Call.ByID(1421909268, phrase);
}

/**
 * BeginRecoveryPhraseChange returns a new recovery phrase for the open vault once verifyOwner accepts the owner; nothing
 * is written until ConfirmRecoveryPhraseChange. Where the vault has a PIN on this device, pin is that PIN whichever way
 * the owner is verified, since the PIN's copy of the new key is wrapped from it; elsewhere pin is empty. Where the
 * device has no way in it can use, current must be the vault's current recovery phrase, which opened it, so whoever
 * finds the vault open cannot take it over.
 */
export function BeginRecoveryPhraseChange(pin: string, current: string): $CancellablePromise<string> {
    return $Call.ByID(392258921, pin, current);
}

/**
 * CancelExtensionLink withdraws the waiting connection key.
 */
export function CancelExtensionLink(): $CancellablePromise<void> {
    return $Call.ByID(2164971577);
}

/**
 * CancelImport drops the staged export and forgets the file.
 */
export function CancelImport(): $CancellablePromise<void> {
    return $Call.ByID(1634143221);
}

/**
 * CancelRecoveryPhraseChange drops the new recovery phrase, leaving the vault as it was.
 */
export function CancelRecoveryPhraseChange(): $CancellablePromise<void> {
    return $Call.ByID(2511183014);
}

/**
 * CancelVaultCreation abandons setting up another vault and returns to the one before it.
 */
export function CancelVaultCreation(): $CancellablePromise<void> {
    return $Call.ByID(4130224917);
}

/**
 * Capabilities reports the features this host offers.
 */
export function Capabilities(): $CancellablePromise<$models.Capabilities> {
    return $Call.ByID(3802279236);
}

/**
 * CheckBreaches checks every password of the vault against known breaches. It fails with breach-checks-off while
 * checks are off and breach-check-unreachable when the service cannot be reached.
 */
export function CheckBreaches(): $CancellablePromise<$models.BreachReport> {
    return $Call.ByID(2028986195);
}

/**
 * CheckPassword reports how many times password appears in known breaches, zero when it is empty or not known. It
 * fails as CheckBreaches does.
 */
export function CheckPassword(password: string): $CancellablePromise<number> {
    return $Call.ByID(4247421927, password);
}

/**
 * CheckSeedPhrase reports the BIP-39 checksum of words as typed. It needs no open vault.
 */
export function CheckSeedPhrase(words: string[] | null): $CancellablePromise<$models.PhraseCheck> {
    return $Call.ByID(736729670, words);
}

/**
 * ChooseBackupFolder records the folder the owner picks and returns after any due backup; false means canceled.
 */
export function ChooseBackupFolder(): $CancellablePromise<boolean> {
    return $Call.ByID(2888804825);
}

/**
 * ChooseIdentityPhoto picks and decodes a picture, replacing the kept one until it is cropped or discarded.
 */
export function ChooseIdentityPhoto(): $CancellablePromise<$models.PhotoDraft> {
    return $Call.ByID(87875043);
}

/**
 * ChooseImportFile picks and previews an export of source; a protected file stays locked until UnlockImportFile.
 */
export function ChooseImportFile(source: string): $CancellablePromise<$models.ImportChoice> {
    return $Call.ByID(2652059268, source);
}

/**
 * ChooseScan picks a picture or PDF and stages it for the editor's save; its content never reaches the interface.
 */
export function ChooseScan(): $CancellablePromise<$models.ScanDraft> {
    return $Call.ByID(2741998602);
}

/**
 * ChooseScanPhoto picks a picture with the host's photo picker and stages it as ChooseScan does.
 */
export function ChooseScanPhoto(): $CancellablePromise<$models.ScanDraft> {
    return $Call.ByID(200161138);
}

/**
 * ChooseStorageMove asks where an open vault goes, in a storage of kind, and holds the answer for
 * MoveStorageLocation; false where the owner chose nothing, which holds no location.
 */
export function ChooseStorageMove(kind: string): $CancellablePromise<boolean> {
    return $Call.ByID(1064516981, kind);
}

/**
 * ChooseSystemAutofill shows the system autofill screen, holding the host until the owner leaves it.
 */
export function ChooseSystemAutofill(): $CancellablePromise<void> {
    return $Call.ByID(2476343232);
}

/**
 * ClearSelection forgets the selected item.
 */
export function ClearSelection(): $CancellablePromise<void> {
    return $Call.ByID(1017897575);
}

/**
 * ConfirmCreation creates the staged vault once phrase matches its recovery key.
 */
export function ConfirmCreation(phrase: string, choice: $models.UnlockChoice): $CancellablePromise<void> {
    return $Call.ByID(1633625027, phrase, choice);
}

/**
 * ConfirmExtensionFills reports whether each password or code a linked extension fills waits for the owner to confirm it.
 */
export function ConfirmExtensionFills(): $CancellablePromise<boolean> {
    return $Call.ByID(4198195827);
}

/**
 * ConfirmRecovery opens the staged vault once accepted confirms every warning its preview gave; a non-empty choice
 * replaces this device's ways in.
 */
export function ConfirmRecovery(accepted: boolean, choice: $models.UnlockChoice): $CancellablePromise<void> {
    return $Call.ByID(3156691533, accepted, choice);
}

/**
 * ConfirmRecoveryPhraseChange seals the open vault for the new recovery phrase once phrase matches it; automatic backups
 * then back it up under the new key at once. Other devices then open the vault with the new phrase; copies saved before
 * keep opening with the old one.
 */
export function ConfirmRecoveryPhraseChange(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(2043228024, phrase);
}

/**
 * ConfirmReveal confirms the owner before the interface shows or copies the secret of the item labelled item: by
 * device authentication where the vault opens with it, else by pin, the vault's PIN, which counts a wrong PIN as the
 * locked screen does. A vault that opens with neither has nothing to confirm with and passes.
 */
export function ConfirmReveal(item: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(1611490407, item, pin);
}

/**
 * ConfirmWithPIN answers the verify or unlock request id with pin; a wrong PIN leaves the request waiting.
 */
export function ConfirmWithPIN(id: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(1490688725, id, pin);
}

/**
 * CopyCardField copies "number", "holder", "expiry", "securityCode", "pin", "bankName", "bankSite", "notes", "billing" or "billing:<part>" of a card.
 */
export function CopyCardField(id: string, field: string): $CancellablePromise<void> {
    return $Call.ByID(4108732235, id, field);
}

/**
 * CopyCredentialField copies one field of the credential id to the clipboard and records the use.
 */
export function CopyCredentialField(id: string, field: string): $CancellablePromise<void> {
    return $Call.ByID(3126298682, id, field);
}

/**
 * CopyExtensionLinkKey copies the waiting key until it is spent, expires, or is canceled or replaced.
 */
export function CopyExtensionLinkKey(): $CancellablePromise<void> {
    return $Call.ByID(1660064991);
}

/**
 * CopyIdentityField copies one value of an identity. A document copies its number.
 */
export function CopyIdentityField(id: string, field: $models.IdentityField): $CancellablePromise<void> {
    return $Call.ByID(1575438035, id, field);
}

/**
 * CopyNote copies a note's body.
 */
export function CopyNote(id: string): $CancellablePromise<void> {
    return $Call.ByID(1787691383, id);
}

/**
 * CopyRecoveryKey copies the staged recovery key while phrase still matches it, as SaveRecoveryKey does.
 */
export function CopyRecoveryKey(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(1417730939, phrase);
}

/**
 * CopyScan copies a scan to the clipboard, hidden from history and cleared on the text delay.
 */
export function CopyScan(id: string): $CancellablePromise<void> {
    return $Call.ByID(801180958, id);
}

/**
 * CopySeedField copies one value of a seed.
 */
export function CopySeedField(id: string, field: $models.SeedField): $CancellablePromise<void> {
    return $Call.ByID(3823222990, id, field);
}

/**
 * CreateCard creates a card in groups and returns its id.
 */
export function CreateCard(input: $models.CardInput, groups: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1414021148, input, groups);
}

/**
 * CreateCredential creates a credential in groups. Autofill links apps, so input names none.
 */
export function CreateCredential(input: $models.CredentialInput, groups: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1678956363, input, groups);
}

/**
 * CreateCredentialFromCodeSetup creates a credential in the default group from the waiting setup token names.
 */
export function CreateCredentialFromCodeSetup(token: string): $CancellablePromise<string> {
    return $Call.ByID(2797724499, token);
}

/**
 * CreateGroup creates a group named name and returns its id.
 */
export function CreateGroup(name: string): $CancellablePromise<string> {
    return $Call.ByID(2709519489, name);
}

/**
 * CreateIdentity creates an identity in groups with its staged scans and returns its id.
 */
export function CreateIdentity(input: $models.IdentityInput, groups: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(4263465516, input, groups);
}

/**
 * CreateNote creates a note in groups and returns its id.
 */
export function CreateNote(input: $models.NoteInput, groups: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1769155242, input, groups);
}

/**
 * CreateSeed creates a seed in groups and returns its id.
 */
export function CreateSeed(input: $models.SeedInput, groups: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3811182727, input, groups);
}

/**
 * CreateVault stages another vault at a free file beside the current one once the owner allows it; nothing is written yet.
 */
export function CreateVault(): $CancellablePromise<$models.StorageChange> {
    return $Call.ByID(3361027554);
}

/**
 * CropIdentityPhoto returns the square at x, y of side size, in preview pixels, as a base64 PNG and empties the slot.
 */
export function CropIdentityPhoto(x: number, y: number, size: number): $CancellablePromise<string> {
    return $Call.ByID(1067825974, x, y, size);
}

/**
 * DeclineConfirmation ends the request id, of any kind, as declined; one that no longer waits fails.
 */
export function DeclineConfirmation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1747084565, id);
}

/**
 * DefaultGroup reports the group new passwords join, empty for none or one the vault no longer holds.
 */
export function DefaultGroup(): $CancellablePromise<string> {
    return $Call.ByID(146963374);
}

/**
 * DeleteGroup reports a malformed or unknown id as an unknown group.
 */
export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(2641600492, id);
}

/**
 * DeleteItem deletes an item of any kind permanently, in the trash or not.
 */
export function DeleteItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(649520838, id);
}

/**
 * DeleteVault irreversibly erases a vault's file and this device's records for it once the owner allows it.
 */
export function DeleteVault(path: string): $CancellablePromise<$models.VaultDeletion> {
    return $Call.ByID(2557419279, path);
}

/**
 * DiscardIdentityPhoto forgets the kept picture.
 */
export function DiscardIdentityPhoto(): $CancellablePromise<void> {
    return $Call.ByID(3808704542);
}

/**
 * DiscardScans forgets every scan chosen since the editor opened.
 */
export function DiscardScans(): $CancellablePromise<void> {
    return $Call.ByID(3218401546);
}

/**
 * DismissCodeSetup forgets the waiting setup token names.
 */
export function DismissCodeSetup(token: string): $CancellablePromise<void> {
    return $Call.ByID(4181256068, token);
}

/**
 * DuplicateItem saves a copy of an item of any kind, named after it, and returns the copy's id.
 */
export function DuplicateItem(id: string): $CancellablePromise<string> {
    return $Call.ByID(2638681916, id);
}

/**
 * EmptyTrash deletes every item in the trash permanently.
 */
export function EmptyTrash(): $CancellablePromise<void> {
    return $Call.ByID(1322811739);
}

/**
 * ExportEncryptedCopy saves an encrypted copy where the owner chooses and records it if the vault is unchanged.
 */
export function ExportEncryptedCopy(): $CancellablePromise<void> {
    return $Call.ByID(1223312309);
}

/**
 * ExportStatus reports whether the last recorded encrypted copy is current, stale or unknown.
 */
export function ExportStatus(): $CancellablePromise<$models.ExportStatus> {
    return $Call.ByID(2268473242);
}

/**
 * ExtensionLinks lists the linked extensions and whether they can reach this app.
 */
export function ExtensionLinks(): $CancellablePromise<$models.ExtensionLinks> {
    return $Call.ByID(2620737492);
}

/**
 * FitConfirmation sets the confirmation panel's height, in points, to the one its page needs.
 */
export function FitConfirmation(height: number): $CancellablePromise<void> {
    return $Call.ByID(4244626944, height);
}

/**
 * ForgetVault drops a vault from the list and keeps its file.
 */
export function ForgetVault(path: string): $CancellablePromise<void> {
    return $Call.ByID(1041517517, path);
}

/**
 * GenerateOneTimeCode derives the current code from setup without reading or keeping vault data.
 */
export function GenerateOneTimeCode(setup: string): $CancellablePromise<$models.OneTimeCode> {
    return $Call.ByID(2739826763, setup);
}

/**
 * GetAppearance reports the appearance and the appearances offered.
 */
export function GetAppearance(): $CancellablePromise<$models.Appearance> {
    return $Call.ByID(3928234356);
}

/**
 * GetAutoBackup reports the automatic backup setting and status.
 */
export function GetAutoBackup(): $CancellablePromise<$models.AutoBackup> {
    return $Call.ByID(3294982011);
}

/**
 * GetAutoLock reports the automatic lock setting.
 */
export function GetAutoLock(): $CancellablePromise<$models.AutoLock> {
    return $Call.ByID(3562416518);
}

/**
 * GetBankDetails reports whether bank details are looked up.
 */
export function GetBankDetails(): $CancellablePromise<$models.BankDetails> {
    return $Call.ByID(1691356278);
}

/**
 * GetBreachChecks reports whether passwords are checked against known breaches.
 */
export function GetBreachChecks(): $CancellablePromise<$models.BreachChecks> {
    return $Call.ByID(892798158);
}

/**
 * GetCardLimits reports the vault core's card bounds.
 */
export function GetCardLimits(): $CancellablePromise<$models.CardLimits> {
    return $Call.ByID(4169195308);
}

/**
 * GetClipboardClearing reports the clipboard clearing setting.
 */
export function GetClipboardClearing(): $CancellablePromise<$models.ClipboardClearing> {
    return $Call.ByID(4030926227);
}

/**
 * GetCodeSetup reports the one-time code setup waiting for the owner.
 */
export function GetCodeSetup(): $CancellablePromise<$models.CodeSetup> {
    return $Call.ByID(377448924);
}

/**
 * GetCredentialLimits reports the vault core's credential bounds.
 */
export function GetCredentialLimits(): $CancellablePromise<$models.CredentialLimits> {
    return $Call.ByID(2617402263);
}

/**
 * GetDockIcon reports whether the Dock icon hides with the window.
 */
export function GetDockIcon(): $CancellablePromise<$models.DockIcon> {
    return $Call.ByID(518185492);
}

/**
 * GetIdentityLimits reports the vault core's identity bounds.
 */
export function GetIdentityLimits(): $CancellablePromise<$models.IdentityLimits> {
    return $Call.ByID(958101948);
}

/**
 * GetIdentityList reports whether the system keeps the vault's accounts.
 */
export function GetIdentityList(): $CancellablePromise<$models.IdentityListSetting> {
    return $Call.ByID(3421652060);
}

/**
 * GetInterfaceSize reports the chosen interface size and the sizes offered.
 */
export function GetInterfaceSize(): $CancellablePromise<$models.InterfaceSize> {
    return $Call.ByID(3080097172);
}

/**
 * GetLanguage reports the languages offered and the one in use.
 */
export function GetLanguage(): $CancellablePromise<$models.LanguageSettings> {
    return $Call.ByID(181901236);
}

/**
 * GetNoteLimits reports the vault core's note bounds.
 */
export function GetNoteLimits(): $CancellablePromise<$models.NoteLimits> {
    return $Call.ByID(23228742);
}

/**
 * GetSeedLimits reports the vault core's seed bounds.
 */
export function GetSeedLimits(): $CancellablePromise<$models.SeedLimits> {
    return $Call.ByID(3891212683);
}

/**
 * GetShortcuts reports changed hotkeys by action; an action missing here keeps the interface's default.
 */
export function GetShortcuts(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3312243161);
}

/**
 * GetSignInStyle reports the sign-in style and the styles offered.
 */
export function GetSignInStyle(): $CancellablePromise<$models.SignInStyle> {
    return $Call.ByID(3170294837);
}

/**
 * GetSiteIcons reports whether website icons load.
 */
export function GetSiteIcons(): $CancellablePromise<$models.SiteIcons> {
    return $Call.ByID(3929642489);
}

/**
 * GetState reports the vault's phase, abandoning an unfinished creation or recovery.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(89553227);
}

/**
 * GetStorage reports where the current vault is kept and the vaults this device knows.
 */
export function GetStorage(): $CancellablePromise<$models.StorageStatus> {
    return $Call.ByID(3263866915);
}

/**
 * GetSystemAutofill reports whether Ravenpass is the device's autofill service and a passkey provider.
 */
export function GetSystemAutofill(): $CancellablePromise<$models.SystemAutofillStatus> {
    return $Call.ByID(1982554829);
}

/**
 * GetTagLimits reports the vault core's tag bounds.
 */
export function GetTagLimits(): $CancellablePromise<$models.TagLimits> {
    return $Call.ByID(308411842);
}

/**
 * GetUnlockMethods reports the ways into the bound vault.
 */
export function GetUnlockMethods(): $CancellablePromise<$models.UnlockMethods> {
    return $Call.ByID(1476140276);
}

/**
 * ImportItems replans the staged export against the current vault and adds what options keep in one all-or-nothing save.
 */
export function ImportItems(options: $models.ImportOptions): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(7502729, options);
}

/**
 * KnowsVault reports whether any location this device knows holds a vault.
 */
export function KnowsVault(): $CancellablePromise<boolean> {
    return $Call.ByID(345006310);
}

/**
 * ListCards reports every card from the index.
 */
export function ListCards(): $CancellablePromise<$models.CardSummary[] | null> {
    return $Call.ByID(3637017141);
}

/**
 * ListCredentials reports every credential from the index.
 */
export function ListCredentials(): $CancellablePromise<$models.CredentialSummary[] | null> {
    return $Call.ByID(1456271760);
}

/**
 * ListGroups reports the open vault's groups.
 */
export function ListGroups(): $CancellablePromise<$models.Group[] | null> {
    return $Call.ByID(267335278);
}

/**
 * ListIdentities reports every identity from the index.
 */
export function ListIdentities(): $CancellablePromise<$models.IdentitySummary[] | null> {
    return $Call.ByID(2108848832);
}

/**
 * ListIdentityAddresses lists the identity addresses a card's billing address can link to.
 */
export function ListIdentityAddresses(): $CancellablePromise<$models.IdentityAddresses[] | null> {
    return $Call.ByID(2968329488);
}

/**
 * ListNotes reports every note from the index.
 */
export function ListNotes(): $CancellablePromise<$models.NoteSummary[] | null> {
    return $Call.ByID(150083795);
}

/**
 * ListSeeds reports every seed from the index.
 */
export function ListSeeds(): $CancellablePromise<$models.SeedSummary[] | null> {
    return $Call.ByID(1486904916);
}

/**
 * ListTrash lists the trash after removing the items kept longer than its period.
 */
export function ListTrash(): $CancellablePromise<$models.Trash> {
    return $Call.ByID(941829340);
}

/**
 * Lock closes the vault and clears what this app put on the clipboard.
 */
export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(324500405);
}

/**
 * LookupBank asks a card's bank site for its name and colour; an unanswered or off lookup is empty, never an error.
 */
export function LookupBank(site: string): $CancellablePromise<$models.BankLookup> {
    return $Call.ByID(2102654562, site);
}

/**
 * LookupSite cuts a credential's website to what the vault matches it by and, when named is set, names it: the name the
 * site declares where website icons load and it answers, else its readable domain. Without named no site is contacted.
 * An address naming no web site is empty, never an error.
 */
export function LookupSite(website: string, named: boolean): $CancellablePromise<$models.SiteLookup> {
    return $Call.ByID(2379475239, website, named);
}

/**
 * MergeCredentials saves input and groups over credential into as UpdateCredential does, with linked apps either
 * credential holds, moves every passkey of from into it, and moves from to the trash, in one save.
 */
export function MergeCredentials(into: string, $from: string, input: $models.CredentialInput, groups: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4289228228, into, $from, input, groups);
}

/**
 * MoveStorageLocation moves an open vault to the location ChooseStorageMove holds.
 */
export function MoveStorageLocation(): $CancellablePromise<$models.StorageChange> {
    return $Call.ByID(1592179435);
}

/**
 * OpenVault makes an existing vault file the owner picks current, once the owner allows it.
 */
export function OpenVault(): $CancellablePromise<$models.StorageChange> {
    return $Call.ByID(3739815246);
}

/**
 * OpenWebsite opens a credential's site in the browser; only http and https addresses are opened.
 */
export function OpenWebsite(address: string): $CancellablePromise<void> {
    return $Call.ByID(2999025583, address);
}

/**
 * PrintRecoveryKey shows the system print dialog for the staged recovery key once phrase matches it, as
 * SaveRecoveryKey does. The page is built in memory and handed only to the host's printer; its buffer is cleared once
 * Print returns, while the host's print view and the system spooler keep their own copies until the job ends.
 */
export function PrintRecoveryKey(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(2269235269, phrase);
}

/**
 * PromptsUnlock reports whether the locked screen may prompt for device unlock now.
 */
export function PromptsUnlock(): $CancellablePromise<boolean> {
    return $Call.ByID(3557226433);
}

/**
 * ReadCard opens the card id with its linked address and records the use.
 */
export function ReadCard(id: string): $CancellablePromise<$models.Card> {
    return $Call.ByID(19115000, id);
}

/**
 * ReadCodeSetup returns the one-time code setup a QR code holds in a picture the owner chooses, for source "file", or
 * in the clipboard's picture, for "clipboard"; empty when the owner cancels the file choice.
 */
export function ReadCodeSetup(source: string): $CancellablePromise<string> {
    return $Call.ByID(1515448784, source);
}

/**
 * ReadCredential opens the credential id and records the use.
 */
export function ReadCredential(id: string): $CancellablePromise<$models.Credential> {
    return $Call.ByID(768130015, id);
}

/**
 * ReadIdentity opens the identity id with its attachment summaries and records the use.
 */
export function ReadIdentity(id: string): $CancellablePromise<$models.Identity> {
    return $Call.ByID(3641676600, id);
}

/**
 * ReadNote opens the note id and records the use.
 */
export function ReadNote(id: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3773259694, id);
}

/**
 * ReadSeed opens the seed id and records the use.
 */
export function ReadSeed(id: string): $CancellablePromise<$models.Seed> {
    return $Call.ByID(4144048099, id);
}

/**
 * RecordSeedCheck records today, in local time, as the day a phrase seed's copy was confirmed.
 */
export function RecordSeedCheck(id: string): $CancellablePromise<void> {
    return $Call.ByID(2048791650, id);
}

/**
 * RecoverFromConfirmation ends the unlock request id and brings the main window forward for recovery.
 */
export function RecoverFromConfirmation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1470705395, id);
}

/**
 * RemovePIN removes the open vault's PIN once verifyOwner accepts the owner, as SetPIN does.
 */
export function RemovePIN(current: string): $CancellablePromise<void> {
    return $Call.ByID(3888613845, current);
}

/**
 * RenameExtension names the linked extension id anew, trimmed; an empty or too long name is refused.
 */
export function RenameExtension(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(429429225, id, name);
}

/**
 * RenameGroup reports a malformed or unknown id as an unknown group and a blank, overlong or taken name as invalid.
 */
export function RenameGroup(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(62115255, id, name);
}

/**
 * RestoreItem brings an item back from the trash.
 */
export function RestoreItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(449074031, id);
}

/**
 * RetryStorage opens the configured location again after it could not be reached.
 */
export function RetryStorage(): $CancellablePromise<void> {
    return $Call.ByID(1785900425);
}

/**
 * RevealImportFile shows the imported export in the file manager.
 */
export function RevealImportFile(): $CancellablePromise<void> {
    return $Call.ByID(2749260552);
}

/**
 * SaveRecoveryKey saves the staged recovery key, of a vault being created or a new phrase, as a text file, only while
 * phrase still matches it.
 */
export function SaveRecoveryKey(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(2226845243, phrase);
}

/**
 * SaveScan writes an unencrypted copy of a scan where the person chooses.
 */
export function SaveScan(id: string): $CancellablePromise<$models.ScanSaved> {
    return $Call.ByID(2250599902, id);
}

/**
 * ScreenshotsAllowed reports whether the owner allows screenshots of the main window.
 */
export function ScreenshotsAllowed(): $CancellablePromise<boolean> {
    return $Call.ByID(3244125265);
}

/**
 * SeedWordlist returns the English BIP-39 list. It needs no open vault.
 */
export function SeedWordlist(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3165029775);
}

/**
 * SelectStorageLocation chooses where a vault not yet created will be kept, in a storage of kind.
 */
export function SelectStorageLocation(kind: string): $CancellablePromise<$models.StorageChange> {
    return $Call.ByID(3186418608, kind);
}

/**
 * SetAppearance records an offered appearance; the host's windows and the interface apply it.
 */
export function SetAppearance(appearance: string): $CancellablePromise<void> {
    return $Call.ByID(77884352, appearance);
}

/**
 * SetAutoBackup records the owner's choices and returns once any backup they make due is written.
 */
export function SetAutoBackup(enabled: boolean, interval: string, keep: number): $CancellablePromise<void> {
    return $Call.ByID(4034688687, enabled, interval, keep);
}

/**
 * SetAutoLock records the automatic lock setting; seconds must be an offered delay.
 */
export function SetAutoLock(enabled: boolean, seconds: number): $CancellablePromise<void> {
    return $Call.ByID(1934122386, enabled, seconds);
}

/**
 * SetBankDetails records whether bank details are looked up.
 */
export function SetBankDetails(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2449876634, enabled);
}

/**
 * SetBiometryUnlock turns device authentication on or off once verifyOwner accepts the owner, as SetPIN does; asking
 * for what is already set changes nothing and asks no one.
 */
export function SetBiometryUnlock(enabled: boolean, current: string): $CancellablePromise<void> {
    return $Call.ByID(2791073867, enabled, current);
}

/**
 * SetBreachChecks records whether passwords are checked against known breaches; turning checks off forgets every
 * answer.
 */
export function SetBreachChecks(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(842237842, enabled);
}

/**
 * SetClipboardClearing records the setting for later copies; a copy already made keeps its delay.
 */
export function SetClipboardClearing(enabled: boolean, seconds: number): $CancellablePromise<void> {
    return $Call.ByID(1438510711, enabled, seconds);
}

/**
 * SetConfirmExtensionFills records whether fills wait for the owner, applied from the next request a linked extension makes.
 */
export function SetConfirmExtensionFills(confirm: boolean): $CancellablePromise<void> {
    return $Call.ByID(4084832307, confirm);
}

/**
 * SetDefaultGroup records the group new passwords join; an empty id clears it.
 */
export function SetDefaultGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(392876910, id);
}

/**
 * SetDockIcon records whether the Dock icon hides with the window, from the next close on.
 */
export function SetDockIcon(hideWithWindow: boolean): $CancellablePromise<void> {
    return $Call.ByID(2831586456, hideWithWindow);
}

/**
 * SetIdentityList records the choice; when on, the system keeps the accounts outside the vault's encryption.
 */
export function SetIdentityList(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1006282744, enabled);
}

/**
 * SetInterfaceSize records one of the offered sizes; the interface applies it.
 */
export function SetInterfaceSize(percent: number): $CancellablePromise<void> {
    return $Call.ByID(4202193936, percent);
}

/**
 * SetItemGroups replaces the membership of an item of either kind.
 */
export function SetItemGroups(id: string, groups: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3270208545, id, groups);
}

/**
 * SetLanguage records one of the offered languages.
 */
export function SetLanguage(language: string): $CancellablePromise<void> {
    return $Call.ByID(2394874664, language);
}

/**
 * SetPIN sets or replaces the open vault's PIN once verifyOwner accepts the owner; current is the PIN or recovery key
 * it may check.
 */
export function SetPIN(pin: string, current: string): $CancellablePromise<void> {
    return $Call.ByID(709540865, pin, current);
}

/**
 * SetPinned pins or unpins an item of either kind.
 */
export function SetPinned(id: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(1597209988, id, pinned);
}

/**
 * SetShortcut records the hotkey for an action; an empty hotkey restores the default.
 */
export function SetShortcut(action: string, hotkey: string): $CancellablePromise<void> {
    return $Call.ByID(162657796, action, hotkey);
}

/**
 * SetSignInStyle records the style, applied from the next extension request.
 */
export function SetSignInStyle(style: string): $CancellablePromise<void> {
    return $Call.ByID(1162474017, style);
}

/**
 * SetSiteIcons records the choice; turning icons off stops fetches and deletes every cached icon.
 */
export function SetSiteIcons(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3215779413, enabled);
}

/**
 * SetTrashRetention sets how many days the trash keeps an item, from vault.MinTrashRetention to
 * vault.MaxTrashRetention, and deletes those kept longer.
 */
export function SetTrashRetention(days: number): $CancellablePromise<void> {
    return $Call.ByID(3257500530, days);
}

/**
 * SiteIcon returns a site's icon, fetching only sites a credential or card of the open vault names.
 */
export function SiteIcon(site: string): $CancellablePromise<$models.SiteIcon> {
    return $Call.ByID(533668420, site);
}

/**
 * SpendBackupCode copies the unused backup code at index, then records it as used.
 */
export function SpendBackupCode(id: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(768751557, id, index);
}

/**
 * SupportDetails reports the operating system and its version.
 */
export function SupportDetails(): $CancellablePromise<$models.SupportDetails> {
    return $Call.ByID(123493057);
}

/**
 * SwitchVault closes the open vault and makes another known vault current.
 */
export function SwitchVault(path: string): $CancellablePromise<void> {
    return $Call.ByID(1992600206, path);
}

/**
 * ThirdPartyNotices returns the license text the build ships, empty when it ships none.
 */
export function ThirdPartyNotices(): $CancellablePromise<string> {
    return $Call.ByID(1815188670);
}

/**
 * TrashImportFile moves the imported export to the Trash.
 */
export function TrashImportFile(): $CancellablePromise<void> {
    return $Call.ByID(3598924251);
}

/**
 * TrashItem moves an item of any kind to the trash.
 */
export function TrashItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(3946147503, id);
}

/**
 * UnlinkExtension removes the linked extension id.
 */
export function UnlinkExtension(id: string): $CancellablePromise<void> {
    return $Call.ByID(2145766962, id);
}

/**
 * Unlock opens the vault with device authentication, prompting in the recorded language.
 */
export function Unlock(): $CancellablePromise<void> {
    return $Call.ByID(4031927462);
}

/**
 * UnlockFromConfirmation unlocks the vault for the unlock request id with device authentication.
 */
export function UnlockFromConfirmation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1925599291, id);
}

/**
 * UnlockImportFile opens the staged protected export and previews it; a wrong password keeps it staged.
 */
export function UnlockImportFile(password: string): $CancellablePromise<$models.ImportPreview> {
    return $Call.ByID(3902321221, password);
}

/**
 * UnlockWithPIN opens the vault with its PIN.
 */
export function UnlockWithPIN(pin: string): $CancellablePromise<void> {
    return $Call.ByID(382696665, pin);
}

/**
 * UpdateCard replaces a card's content and membership as a whole.
 */
export function UpdateCard(id: string, input: $models.CardInput, groups: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(818511173, id, input, groups);
}

/**
 * UpdateCredential saves input and groups over the credential id and drops removedPasskeys in one save.
 */
export function UpdateCredential(id: string, input: $models.CredentialInput, groups: string[] | null, removedPasskeys: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(878996714, id, input, groups, removedPasskeys);
}

/**
 * UpdateIdentity replaces an identity's content, membership and scans in one save.
 */
export function UpdateIdentity(id: string, input: $models.IdentityInput, groups: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(569047613, id, input, groups);
}

/**
 * UpdateNote replaces a note's content and membership as a whole.
 */
export function UpdateNote(id: string, input: $models.NoteInput, groups: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2701512883, id, input, groups);
}

/**
 * UpdateSeed replaces a seed's content and membership; the checked day survives only unchanged phrase words.
 */
export function UpdateSeed(id: string, input: $models.SeedInput, groups: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2310841342, id, input, groups);
}
