package api

// failure is a code the shared interface words in the user's language.
type failure string

const (
	failureGeneral                  failure = "general"
	failureWindowUnavailable        failure = "window-unavailable"
	failureAuthenticationCanceled   failure = "authentication-canceled"
	failureAuthenticationFailed     failure = "authentication-failed"
	failureUnlockUnavailable        failure = "unlock-unavailable"
	failureUnlockKeyMissing         failure = "unlock-key-missing"
	failureVaultLocked              failure = "vault-locked"
	failureVaultExists              failure = "vault-exists"
	failureSetupInProgress          failure = "setup-in-progress"
	failureSetupNotActive           failure = "setup-not-active"
	failureNoLocalVault             failure = "no-local-vault"
	failureRecoveryNeedsConfirm     failure = "recovery-needs-confirmation"
	failureRecoveryReplacedKey      failure = "recovery-replaced-key"
	failureKeyChangeUnfinished      failure = "key-change-unfinished"
	failureKeyChangeUncertain       failure = "key-change-uncertain"
	failureRecoveryChanged          failure = "recovery-changed"
	failureRecoveryPhraseInvalid    failure = "recovery-phrase-invalid"
	failureRecoveryKeyMismatch      failure = "recovery-key-mismatch"
	failureRecoveryKeyNotSaved      failure = "recovery-key-not-saved"
	failureRecoveryKeySaveFailed    failure = "recovery-key-save-failed"
	failureRecoveryKeyCopyFailed    failure = "recovery-key-copy-failed"
	failureRecoveryKeyPrintFailed   failure = "recovery-key-print-failed"
	failureVaultChanged             failure = "vault-changed"
	failureVaultMissing             failure = "vault-missing"
	failureSaveUnconfirmed          failure = "save-unconfirmed"
	failureAuthenticationInvalid    failure = "authentication-invalid"
	failureUnsupportedFormat        failure = "unsupported-format"
	failureMalformedVault           failure = "malformed-vault"
	failureInvalidItem              failure = "invalid-item"
	failureInvalidCode              failure = "invalid-code"
	failureNoCode                   failure = "no-code"
	failureCodeSetupExpired         failure = "code-setup-expired"
	failureQRCodeMissing            failure = "qr-code-missing"
	failureQRCodeNotSetup           failure = "qr-code-not-setup"
	failureQRCodeAmbiguous          failure = "qr-code-ambiguous"
	failureResourceLimit            failure = "resource-limit"
	failurePasskeysFull             failure = "passkeys-full"
	failureBreachChecksOff          failure = "breach-checks-off"
	failureBreachCheckUnreachable   failure = "breach-check-unreachable"
	failurePermissionDenied         failure = "permission-denied"
	failureFileSizeInvalid          failure = "file-size-invalid"
	failureFileUnverified           failure = "file-unverified"
	failureFileNotSelected          failure = "file-not-selected"
	failureLocationNotSelected      failure = "location-not-selected"
	failureItemUnreadable           failure = "item-unreadable"
	failurePhotoUnsupported         failure = "photo-unsupported"
	failurePhotoTooLarge            failure = "photo-too-large"
	failureScanUnsupported          failure = "scan-unsupported"
	failureScanTooLarge             failure = "scan-too-large"
	failureScanLimit                failure = "scan-limit"
	failureFieldNotCopyable         failure = "field-not-copyable"
	failureFieldEmpty               failure = "field-empty"
	failureCopyFailed               failure = "copy-failed"
	failureWebsiteMissing           failure = "website-missing"
	failureWebsiteUnsupported       failure = "website-unsupported"
	failureWebsiteOpenFailed        failure = "website-open-failed"
	failureExportCanceled           failure = "export-canceled"
	failureExportStale              failure = "export-stale"
	failureExportUnconfirmed        failure = "export-unconfirmed"
	failureExportUnrecorded         failure = "export-unrecorded"
	failureStorageUnavailable       failure = "storage-unavailable"
	failureStorageSelectionInvalid  failure = "storage-selection-invalid"
	failureStorageOccupied          failure = "storage-occupied"
	failureStorageSameLocation      failure = "storage-same-location"
	failureStorageKindUnsupported   failure = "storage-kind-unsupported"
	failureStoragePathInvalid       failure = "storage-path-invalid"
	failureMoveUnverified           failure = "move-unverified"
	failureSecondCopy               failure = "second-copy"
	failureOlderCopy                failure = "older-copy"
	failureVaultDiverged            failure = "vault-diverged"
	failureVaultKeyReplaced         failure = "vault-key-replaced"
	failureWitnessMissing           failure = "witness-missing"
	failureVaultUnknown             failure = "vault-unknown"
	failureNoOtherVault             failure = "no-other-vault"
	failureGroupUnknown             failure = "group-unknown"
	failureGroupNameInvalid         failure = "group-name-invalid"
	failurePINInvalid               failure = "pin-invalid"
	failurePINWrong                 failure = "pin-wrong"
	failurePINTooSoon               failure = "pin-too-soon"
	failurePINRemoved               failure = "pin-removed"
	failurePINMissing               failure = "pin-missing"
	failureBiometryUnavailable      failure = "biometry-unavailable"
	failureBiometryDisabled         failure = "biometry-disabled"
	failureUnlockMethodRequired     failure = "unlock-method-required"
	failureUnlockRecordUnreadable   failure = "unlock-record-unreadable"
	failureOwnerUnverified          failure = "owner-unverified"
	failureLanguageUnsupported      failure = "language-unsupported"
	failureClearDelayUnsupported    failure = "clear-delay-unsupported"
	failureAutoLockDelayUnsupported failure = "auto-lock-delay-unsupported"
	failureBackupChoiceUnsupported  failure = "backup-choice-unsupported"
	failureBackupFolderMissing      failure = "backup-folder-missing"
	failureSignInStyleUnsupported   failure = "sign-in-style-unsupported"
	failureAppearanceUnsupported    failure = "appearance-unsupported"
	failureShortcutInvalid          failure = "shortcut-invalid"
	failureImportSourceUnknown      failure = "import-source-unknown"
	failureImportUnrecognized       failure = "import-unrecognized"
	failureImportTooLarge           failure = "import-too-large"
	failureImportAccountBound       failure = "import-account-bound"
	failureImportPasswordWrong      failure = "import-password-wrong"
	failureImportEncryption         failure = "import-encryption-unsupported"
	failureImportNotActive          failure = "import-not-active"
	failureImportEmpty              failure = "import-empty"
	failureImportLimit              failure = "import-limit"
	failureImportTrashFailed        failure = "import-trash-failed"
	failureImportRevealFailed       failure = "import-reveal-failed"
	failureLinkExpired              failure = "link-expired"
	failureLinkCanceled             failure = "link-canceled"
	failureLinkUnavailable          failure = "link-unavailable"
	failureExtensionNotFound        failure = "extension-not-found"
	failureExtensionNameInvalid     failure = "extension-name-invalid"
	failureConfirmationEnded        failure = "confirmation-ended"
)

// failurePrefix marks an error message the interface can translate; any other is unexpected.
const failurePrefix = "ravenpass:"

func (code failure) Error() string {
	return failurePrefix + string(code)
}

func fail(code failure) error {
	return code
}
